# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e8f6d62f274208af6c77ebae43ebb8a30e26c59c6a8d9d7d2b00328e407ae87a01976abb21c99ec9c5b57c55a1f158fa3081c0f023599bb3dde537ed0e4a08a

test:
  secret_key_base: bd0c942165cbb99fd78bed5e32ab0d5138e02d87655603f3142807169191cea873b2a4fd779cc07d1027b295b42ba734afeb9df9539e168a0578c714c8f2f836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
